### ISSUE TITLE
Suport New Web API NMT(Neural Machine Translation)

### ISSUE THREAD

**Issue by miurahr** [miurahr/omegat-textra-plugin#5]
NICT released NMT rather than SMT in July  2017. This lead change of Web API.
The plugin should update to adapt new API.

related https://github.com/miurahr/omegat-textra-plugin/issues/4#issuecomment-435559858

**Comment by hsugawa8651** [comment]
現時点の「みん翻」の説明によると、例えば、汎用NMT【英語 - 日本語] は、WebAPI の request URLの末尾が generalN_en_ja です。generic_en_ja や minna_en_ja では code=525 や 530 が各々返され、result の text要素は空でした。

WebAPI として genericN を決め打ちする形で試してみました。
https://github.com/hsugawa8651/omegat-textra-plugin
v0.4n です。
正しく翻訳結果が正しく返ってきます。

**Comment by miurahr** [comment]
@hsugawa8651 master ブランチのHEADに、修正をいれてみました。
ご確認をおねがいできますでしょうか。

## 既知の問題
翻訳まわりは、まだ修正が必要です。

**Comment by hsugawa8651** [comment]
ありがとうございます。しかし、
genericN では NGで、generalN です。
(上コメントの末尾は混乱して genericNと誤記しました。修正しました）

**Comment by miurahr** [comment]
これでどうでしょう? @hsugawa8651 
https://github.com/miurahr/omegat-textra-plugin/commit/66c3914931ecc4ee7978a3d7f737b59e665b7090

**Comment by hsugawa8651** [comment]
【英語 → 日本語】を試しましたが、翻訳結果は表示されます。
ただし、Set Options メニューを選んでも、何も表示されません (という動作でよろしいですか？）

**Comment by miurahr** [comment]
エラーになっちゃってますね。動作確認できる環境になかったので、なにかがわるいようです。
実行時のログをつけていただけるとたすかります。

```
80625: 情報: メニュー項目 optionsMachineTranslateMenu をクリック (LOG_MENU_CLICK)
80625: エラー: Uncatched exception in thread [AWT-EventQueue-0] 
80625: エラー: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key GenericModeToolTip 
80625: エラー: 	at java.util.ResourceBundle.getObject(ResourceBundle.java:450) 
80625: エラー: 	at java.util.ResourceBundle.getString(ResourceBundle.java:407) 
80625: エラー: 	at tokyo.northside.omegat.textra.dialog.TextraOptionDialog.$$$setupUI$$$(TextraOptionDialog.java:209) 
80625: エラー: 	at tokyo.northside.omegat.textra.dialog.TextraOptionDialog.<init>(TextraOptionDialog.java:148) 
80625: エラー: 	at tokyo.northside.omegat.textra.OmegatTextraMachineTranslation.actionPerformed(OmegatTextraMachineTranslation.java:150) 
80625: エラー: 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) 
80625: エラー: 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) 
80625: エラー: 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) 
80625: エラー: 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) 
80625: エラー: 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) 
80625: エラー: 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842) 
80625: エラー: 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886) 
80625: エラー: 	at java.awt.Component.processMouseEvent(Component.java:6539) 
80625: エラー: 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) 
80625: エラー: 	at java.awt.Component.processEvent(Component.java:6304) 
80625: エラー: 	at java.awt.Container.processEvent(Container.java:2239) 
80625: エラー: 	at java.awt.Component.dispatchEventImpl(Component.java:4889) 
80625: エラー: 	at java.awt.Container.dispatchEventImpl(Container.java:2297) 
80625: エラー: 	at java.awt.Component.dispatchEvent(Component.java:4711) 
80625: エラー: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) 
80625: エラー: 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) 
80625: エラー: 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) 
80625: エラー: 	at java.awt.Container.dispatchEventImpl(Container.java:2283) 
80625: エラー: 	at java.awt.Window.dispatchEventImpl(Window.java:2746) 
80625: エラー: 	at java.awt.Component.dispatchEvent(Component.java:4711) 
80625: エラー: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) 
80625: エラー: 	at java.awt.EventQueue.access$500(EventQueue.java:97) 
80625: エラー: 	at java.awt.EventQueue$3.run(EventQueue.java:709) 
80625: エラー: 	at java.awt.EventQueue$3.run(EventQueue.java:703) 
80625: エラー: 	at java.security.AccessController.doPrivileged(Native Method) 
80625: エラー: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) 
80625: エラー: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) 
80625: エラー: 	at java.awt.EventQueue$4.run(EventQueue.java:733) 
80625: エラー: 	at java.awt.EventQueue$4.run(EventQueue.java:731) 
80625: エラー: 	at java.security.AccessController.doPrivileged(Native Method) 
80625: エラー: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) 
80625: エラー: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) 
80625: エラー: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) 
80625: エラー: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
80625: エラー: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
80625: エラー: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
80625: エラー: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
80625: エラー: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

**Comment by miurahr** [comment]
修正しました。わたしの手元ではうごいているようです。
