### ISSUE TITLE
[BUG] Sequence of errors when getting a segment's translation

### ISSUE THREAD

**Issue by malvarenga123** [miurahr/omegat-textra-plugin#99]
**Describe the bug**
Getting the following errors on the console when trying to get the translation of a segment:
```
20834: Error: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "resultset" (class tokyo.northside.omegat.textra.TextraApiCli ent$ResultSet), not marked as ignorable (one known property: "result"])
20834: Error:  at [Source: (BufferedInputStream); line: 1, column: 15] (through reference chain: tokyo.northside.omegat.textra.TextraApiClient$ResultSet["result set"])
20834: Error:   at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
20834: Error:   at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
20834: Error:   at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
20834: Error:   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
20834: Error:   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
20834: Error:   at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
20834: Error:   at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
20834: Error:   at com.fasterxml.jackson.databind.deser.DefaultDeserializationCo ntext.readRootValue(DefaultDeserializationContext.java:323)
20834: Error:   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
20834: Error:   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
20834: Error:   at tokyo.northside.omegat.textra.TextraApiClient.executeTranslation(TextraApiClient.java:182)
20834: Error:   at tokyo.northside.omegat.textra.OmegatTextraMachineTranslation.translate(OmegatTextraMachineTranslation.java:147)
20834: Error:   at tokyo.northside.omegat.textra.OmegatTextraMachineTranslation.getTranslation(OmegatTextraMachineTranslation.java:171)
20834: Error:   at org.omegat.gui.exttrans.MachineTranslateTextArea$FindThread.getTranslation(MachineTranslateTextArea.java:205)
20834: Error:   at org.omegat.gui.exttrans.MachineTranslateTextArea$FindThread.search(MachineTranslateTextArea.java:189)
20834: Error:   at org.omegat.gui.exttrans.MachineTranslateTextArea$FindThread.search(MachineTranslateTextArea.java:164)
20834: Error:   at org.omegat.gui.common.EntryInfoSearchThread.run(EntryInfoSearchThread.java:96)
```

**To Reproduce**
Just change to a new untranslated segment and wait. Languages used are from en-US to pt-BR.

**Expected behavior**
Get the machine translation.

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Java: Java 8u321
 - OmegaT: 5.7.1
 - Textra Plugin: 2022.2.2

**Additional context**
This happens with both 2022.2 and 2020.2 (which was the one I was using previously).

**Comment by miurahr** [comment]
The fix is out.
